### ISSUE TITLE
Tabs opened in background get marked as last active

### ISSUE THREAD

**Issue by poirier** [davidsierradz/tst-add-last-active-class-to-tab#1]
Extension Version 1.1, Firefox 69.0.2

If I open a tab in the background, say by Control-Clicking it, the new tab gets marked as last active, and the previously last active tab is no longer marked.

(I expected that a tab wouldn't get marked last active unless I had visited it first.)

**Comment by davidsierradz** [comment]
Hi. I'm using the `Tab` property `lastAccessed` (see: [tabs.Tab - Mozilla | MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/Tab#Type)) to determine the tab accessed before the current one. So, if Firefox is updating this property when it shouldn't  I can't do anything on my side.
